import Database from "better-sqlite3";
import path from "path";

const DB_PATH = process.env.DATABASE_URL || path.join(process.cwd(), "agentstore.db");

let db: Database.Database;

export function getDb(): Database.Database {
  if (!db) {
    db = new Database(DB_PATH);
    db.pragma("journal_mode = WAL");
    db.pragma("foreign_keys = ON");
    initializeDb(db);
  }
  return db;
}

function initializeDb(db: Database.Database) {
  db.exec(`
    CREATE TABLE IF NOT EXISTS agents (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT NOT NULL,
      category TEXT NOT NULL,
      price_per_call REAL NOT NULL,
      input_schema TEXT,
      output_schema TEXT,
      endpoint TEXT NOT NULL,
      locus_wallet_address TEXT NOT NULL,
      status TEXT DEFAULT 'online',
      rating REAL DEFAULT 5.0,
      total_jobs INTEGER DEFAULT 0,
      total_earned REAL DEFAULT 0.0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS transactions (
      id TEXT PRIMARY KEY,
      task_id TEXT NOT NULL,
      buyer_agent_id TEXT NOT NULL,
      seller_agent_id TEXT NOT NULL,
      amount REAL NOT NULL,
      negotiated_from REAL,
      negotiated_to REAL,
      status TEXT DEFAULT 'pending',
      locus_tx_id TEXT,
      tx_hash TEXT,
      task_description TEXT,
      result TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      completed_at TEXT
    );

    CREATE TABLE IF NOT EXISTS tasks (
      id TEXT PRIMARY KEY,
      user_input TEXT NOT NULL,
      status TEXT DEFAULT 'decomposing',
      sub_tasks TEXT,
      final_result TEXT,
      total_cost REAL DEFAULT 0.0,
      created_at TEXT DEFAULT (datetime('now')),
      completed_at TEXT
    );
  `);

  const count = db.prepare("SELECT COUNT(*) as count FROM agents").get() as { count: number };
  if (count.count === 0) {
    seedAgents(db);
  }
}

function seedAgents(db: Database.Database) {
  const insert = db.prepare(`
    INSERT INTO agents (id, name, description, category, price_per_call, endpoint, locus_wallet_address, status, rating, total_jobs, total_earned)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  const agents = [
    // ── Original 5 agents (unchanged) ──────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "SummarizeBot",
      description: "Condenses long documents, articles, and text into clear, structured summaries with key takeaways.",
      category: "summarization",
      price_per_call: 0.005,
      endpoint: "/api/agents/summarizer/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.9,
      jobs: 23,
      earned: 0.115,
    },
    {
      id: crypto.randomUUID(),
      name: "TranslateBot",
      description: "Translates text between 50+ languages while preserving tone and context. Specializes in technical and business content.",
      category: "translation",
      price_per_call: 0.004,
      endpoint: "/api/agents/translator/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.8,
      jobs: 18,
      earned: 0.072,
    },
    {
      id: crypto.randomUUID(),
      name: "CodeReviewBot",
      description: "Reviews code for bugs, security issues, performance problems, and style. Supports Python, TypeScript, Go, and Rust.",
      category: "code-review",
      price_per_call: 0.008,
      endpoint: "/api/agents/code-reviewer/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.7,
      jobs: 12,
      earned: 0.096,
    },
    {
      id: crypto.randomUUID(),
      name: "ResearchBot",
      description: "Conducts deep research on any topic using web search and data analysis. Returns structured reports with citations.",
      category: "research",
      price_per_call: 0.012,
      endpoint: "/api/agents/researcher/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.6,
      jobs: 8,
      earned: 0.096,
    },
    {
      id: crypto.randomUUID(),
      name: "CopywriterBot",
      description: "Generates marketing copy, blog posts, social media content, and email sequences optimized for engagement.",
      category: "content",
      price_per_call: 0.006,
      endpoint: "/api/agents/copywriter/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.8,
      jobs: 15,
      earned: 0.09,
    },

    // ── Additional summarization agents ────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "BriefMakerBot",
      description: "Creates executive briefs from lengthy reports, extracting action items and decisions for busy stakeholders.",
      category: "summarization",
      price_per_call: 0.006,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.5,
      jobs: 42,
      earned: 0.252,
    },
    {
      id: crypto.randomUUID(),
      name: "TLDRAgent",
      description: "Generates ultra-concise one-paragraph summaries optimized for Slack and email digests.",
      category: "summarization",
      price_per_call: 0.003,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.7,
      jobs: 87,
      earned: 0.261,
    },

    // ── Additional translation agents ──────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "PolyglotBot",
      description: "Specializes in simultaneous multi-language translation, outputting up to 10 languages in a single call.",
      category: "translation",
      price_per_call: 0.007,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.4,
      jobs: 34,
      earned: 0.238,
    },
    {
      id: crypto.randomUUID(),
      name: "LocalizeBot",
      description: "Adapts content for regional markets with cultural nuance, idioms, and locale-specific formatting.",
      category: "translation",
      price_per_call: 0.009,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "busy",
      rating: 4.6,
      jobs: 21,
      earned: 0.189,
    },

    // ── Additional code-review agents ──────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "LintMasterBot",
      description: "Runs deep static analysis across JavaScript, TypeScript, and Python codebases with auto-fix suggestions.",
      category: "code-review",
      price_per_call: 0.005,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.3,
      jobs: 65,
      earned: 0.325,
    },
    {
      id: crypto.randomUUID(),
      name: "RefactorBot",
      description: "Identifies code smells and suggests refactoring patterns to improve maintainability and reduce complexity.",
      category: "code-review",
      price_per_call: 0.010,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.8,
      jobs: 29,
      earned: 0.290,
    },

    // ── Additional research agents ─────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "DeepDiveBot",
      description: "Performs exhaustive literature reviews and competitive analyses with source credibility scoring.",
      category: "research",
      price_per_call: 0.018,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.5,
      jobs: 14,
      earned: 0.252,
    },
    {
      id: crypto.randomUUID(),
      name: "FactCheckBot",
      description: "Verifies claims against trusted sources and returns confidence scores with supporting evidence links.",
      category: "research",
      price_per_call: 0.008,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.9,
      jobs: 53,
      earned: 0.424,
    },

    // ── Additional content agents ──────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "BlogForgeBot",
      description: "Produces long-form blog articles with SEO-optimized structure, internal linking suggestions, and meta descriptions.",
      category: "content",
      price_per_call: 0.010,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.6,
      jobs: 38,
      earned: 0.380,
    },
    {
      id: crypto.randomUUID(),
      name: "SocialSparkBot",
      description: "Crafts platform-specific social media posts for Twitter, LinkedIn, and Instagram with hashtag optimization.",
      category: "content",
      price_per_call: 0.004,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.2,
      jobs: 112,
      earned: 0.448,
    },

    // ── Data Extraction agents ─────────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "ScraperBot",
      description: "Extracts structured data from web pages, PDFs, and documents into clean JSON or CSV formats.",
      category: "data-extraction",
      price_per_call: 0.007,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.5,
      jobs: 76,
      earned: 0.532,
    },
    {
      id: crypto.randomUUID(),
      name: "TableParserBot",
      description: "Detects and extracts tabular data from images, scanned documents, and unstructured text with high accuracy.",
      category: "data-extraction",
      price_per_call: 0.012,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.3,
      jobs: 31,
      earned: 0.372,
    },
    {
      id: crypto.randomUUID(),
      name: "EntityExtractBot",
      description: "Identifies and extracts named entities—people, organizations, dates, and amounts—from unstructured text.",
      category: "data-extraction",
      price_per_call: 0.005,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "offline",
      rating: 4.1,
      jobs: 19,
      earned: 0.095,
    },

    // ── Sentiment Analysis agents ──────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "MoodReaderBot",
      description: "Analyzes text sentiment with fine-grained emotion detection across 12 emotional dimensions.",
      category: "sentiment-analysis",
      price_per_call: 0.004,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.6,
      jobs: 91,
      earned: 0.364,
    },
    {
      id: crypto.randomUUID(),
      name: "ReviewPulseBot",
      description: "Processes customer reviews and feedback at scale, generating sentiment trends and highlight reels.",
      category: "sentiment-analysis",
      price_per_call: 0.006,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.4,
      jobs: 47,
      earned: 0.282,
    },
    {
      id: crypto.randomUUID(),
      name: "BrandSentinelBot",
      description: "Monitors brand mentions and classifies public sentiment as positive, negative, or neutral with context summaries.",
      category: "sentiment-analysis",
      price_per_call: 0.008,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.7,
      jobs: 63,
      earned: 0.504,
    },

    // ── Image Generation agents ────────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "PixelForgeBot",
      description: "Generates high-resolution images from text prompts with style control for photorealistic, illustration, and abstract modes.",
      category: "image-generation",
      price_per_call: 0.020,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.8,
      jobs: 134,
      earned: 2.680,
    },
    {
      id: crypto.randomUUID(),
      name: "IconSmithBot",
      description: "Creates SVG icons and small graphics optimized for web and mobile interfaces from natural language descriptions.",
      category: "image-generation",
      price_per_call: 0.010,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.3,
      jobs: 56,
      earned: 0.560,
    },
    {
      id: crypto.randomUUID(),
      name: "BannerBot",
      description: "Designs marketing banners and social media graphics with brand-consistent layouts and typography.",
      category: "image-generation",
      price_per_call: 0.015,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "busy",
      rating: 4.5,
      jobs: 40,
      earned: 0.600,
    },

    // ── Audio Transcription agents ─────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "TranscribeBot",
      description: "Converts audio and video files to accurate text transcripts with speaker diarization and timestamps.",
      category: "audio-transcription",
      price_per_call: 0.015,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.7,
      jobs: 82,
      earned: 1.230,
    },
    {
      id: crypto.randomUUID(),
      name: "MeetingNotesBot",
      description: "Transcribes meeting recordings and produces structured minutes with action items and participant attributions.",
      category: "audio-transcription",
      price_per_call: 0.018,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.9,
      jobs: 48,
      earned: 0.864,
    },
    {
      id: crypto.randomUUID(),
      name: "PodcastDigestBot",
      description: "Transcribes podcast episodes and generates show notes, chapter markers, and key quote highlights.",
      category: "audio-transcription",
      price_per_call: 0.020,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "offline",
      rating: 4.2,
      jobs: 11,
      earned: 0.220,
    },

    // ── Legal agents ───────────────────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "ContractScanBot",
      description: "Reviews contracts and legal documents, flagging risky clauses, missing terms, and compliance issues.",
      category: "legal",
      price_per_call: 0.022,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.6,
      jobs: 27,
      earned: 0.594,
    },
    {
      id: crypto.randomUUID(),
      name: "ComplianceBot",
      description: "Checks documents and policies against GDPR, HIPAA, SOC 2, and other regulatory frameworks.",
      category: "legal",
      price_per_call: 0.025,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.8,
      jobs: 35,
      earned: 0.875,
    },
    {
      id: crypto.randomUUID(),
      name: "NDASummaryBot",
      description: "Parses NDAs and confidentiality agreements, extracting key obligations, durations, and carve-outs.",
      category: "legal",
      price_per_call: 0.014,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.4,
      jobs: 18,
      earned: 0.252,
    },

    // ── Finance agents ─────────────────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "LedgerBot",
      description: "Categorizes transactions, reconciles accounts, and generates financial summaries from raw banking data.",
      category: "finance",
      price_per_call: 0.012,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.5,
      jobs: 44,
      earned: 0.528,
    },
    {
      id: crypto.randomUUID(),
      name: "ForecastBot",
      description: "Builds revenue and expense forecasts using historical data with configurable growth assumptions.",
      category: "finance",
      price_per_call: 0.018,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.7,
      jobs: 22,
      earned: 0.396,
    },
    {
      id: crypto.randomUUID(),
      name: "InvoiceParserBot",
      description: "Extracts line items, totals, tax info, and payment terms from invoices in PDF or image format.",
      category: "finance",
      price_per_call: 0.008,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.3,
      jobs: 67,
      earned: 0.536,
    },

    // ── SEO agents ─────────────────────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "KeywordBot",
      description: "Researches and clusters keywords by search intent, providing volume estimates and difficulty scores.",
      category: "seo",
      price_per_call: 0.006,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.4,
      jobs: 98,
      earned: 0.588,
    },
    {
      id: crypto.randomUUID(),
      name: "MetaTagBot",
      description: "Generates optimized title tags, meta descriptions, and Open Graph tags for any URL or content piece.",
      category: "seo",
      price_per_call: 0.003,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.6,
      jobs: 143,
      earned: 0.429,
    },
    {
      id: crypto.randomUUID(),
      name: "SiteAuditBot",
      description: "Crawls websites and identifies SEO issues including broken links, missing alt text, and slow page speed.",
      category: "seo",
      price_per_call: 0.015,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "offline",
      rating: 3.9,
      jobs: 8,
      earned: 0.120,
    },

    // ── QA Testing agents ──────────────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "TestGenBot",
      description: "Generates unit and integration test suites from source code with edge case coverage analysis.",
      category: "qa-testing",
      price_per_call: 0.010,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.5,
      jobs: 52,
      earned: 0.520,
    },
    {
      id: crypto.randomUUID(),
      name: "RegressionBot",
      description: "Identifies potential regression risks from code diffs and suggests targeted test scenarios.",
      category: "qa-testing",
      price_per_call: 0.009,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.7,
      jobs: 33,
      earned: 0.297,
    },
    {
      id: crypto.randomUUID(),
      name: "APIValidatorBot",
      description: "Tests REST and GraphQL endpoints against OpenAPI specs, reporting schema violations and latency issues.",
      category: "qa-testing",
      price_per_call: 0.011,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.3,
      jobs: 25,
      earned: 0.275,
    },

    // ── Data Visualization agents ──────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "ChartBot",
      description: "Transforms raw datasets into interactive charts and graphs with automatic axis labeling and color theming.",
      category: "data-visualization",
      price_per_call: 0.008,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.6,
      jobs: 71,
      earned: 0.568,
    },
    {
      id: crypto.randomUUID(),
      name: "DashboardBot",
      description: "Generates dashboard layouts with KPI cards, trend lines, and comparison panels from structured data.",
      category: "data-visualization",
      price_per_call: 0.014,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.8,
      jobs: 39,
      earned: 0.546,
    },
    {
      id: crypto.randomUUID(),
      name: "InfographicBot",
      description: "Creates infographic-style visual summaries from reports, stats, and key findings.",
      category: "data-visualization",
      price_per_call: 0.016,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "busy",
      rating: 4.2,
      jobs: 15,
      earned: 0.240,
    },

    // ── Cybersecurity agents ───────────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "VulnScanBot",
      description: "Scans codebases and dependencies for known CVEs, generating prioritized remediation reports.",
      category: "cybersecurity",
      price_per_call: 0.020,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.7,
      jobs: 58,
      earned: 1.160,
    },
    {
      id: crypto.randomUUID(),
      name: "PhishDetectBot",
      description: "Analyzes emails and URLs for phishing indicators using heuristic and ML-based detection models.",
      category: "cybersecurity",
      price_per_call: 0.005,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.9,
      jobs: 120,
      earned: 0.600,
    },
    {
      id: crypto.randomUUID(),
      name: "SecAuditBot",
      description: "Performs security audits on infrastructure configs, IAM policies, and network rules for cloud environments.",
      category: "cybersecurity",
      price_per_call: 0.022,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.4,
      jobs: 16,
      earned: 0.352,
    },

    // ── Customer Support agents ────────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "TicketTriageBot",
      description: "Classifies incoming support tickets by urgency, category, and suggested assignee with auto-tagging.",
      category: "customer-support",
      price_per_call: 0.003,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.5,
      jobs: 148,
      earned: 0.444,
    },
    {
      id: crypto.randomUUID(),
      name: "FAQBot",
      description: "Answers common customer questions using a knowledge base, escalating complex issues to human agents.",
      category: "customer-support",
      price_per_call: 0.002,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.1,
      jobs: 130,
      earned: 0.260,
    },

    // ── Email Automation agents ────────────────────────────────────────
    {
      id: crypto.randomUUID(),
      name: "OutreachBot",
      description: "Drafts personalized cold outreach emails using prospect data, with A/B subject line variants.",
      category: "email-automation",
      price_per_call: 0.005,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.3,
      jobs: 89,
      earned: 0.445,
    },
    {
      id: crypto.randomUUID(),
      name: "NewsletterBot",
      description: "Compiles curated newsletter editions from content feeds with engaging intros and section formatting.",
      category: "email-automation",
      price_per_call: 0.007,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.6,
      jobs: 55,
      earned: 0.385,
    },
    {
      id: crypto.randomUUID(),
      name: "FollowUpBot",
      description: "Generates context-aware follow-up email sequences based on prior conversation history and engagement signals.",
      category: "email-automation",
      price_per_call: 0.004,
      endpoint: "/api/agents/generic/execute",
      wallet: "0x6cd8d19ff7f66d2045e60908f4d77ccfb9edfec6",
      status: "online",
      rating: 4.5,
      jobs: 72,
      earned: 0.288,
    },
  ];

  const insertMany = db.transaction(() => {
    for (const a of agents) {
      insert.run(a.id, a.name, a.description, a.category, a.price_per_call, a.endpoint, a.wallet, a.status, a.rating, a.jobs, a.earned);
    }
  });

  insertMany();
}
